--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2021. 12. 02. 17:12:20
-- Server version: 5.5.5-10.4.6-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE forma1;

--
-- Drop table `versenyzok`
--
DROP TABLE IF EXISTS versenyzok;

--
-- Set default database
--
USE forma1;

--
-- Create table `versenyzok`
--
CREATE TABLE versenyzok (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  nev VARCHAR(30) NOT NULL,
  nemzet VARCHAR(10) DEFAULT NULL,
  szuletes DATE NOT NULL,
  magassag TINYINT(3) UNSIGNED DEFAULT NULL,
  csapat INT(11) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE versenyzok 
  ADD CONSTRAINT fk_csapatok_csapat FOREIGN KEY (csapat)
    REFERENCES csapatok(csapatID);

-- 
-- Dumping data for table versenyzok
--
INSERT INTO versenyzok VALUES
(1, 'Lewis Hamilton', 'angol', '1985-01-07', 174, 1),
(2, 'Valtteri Bottas', 'finn', '1989-08-28', NULL, 1),
(3, 'Sebastian Vettel', 'német', '1987-07-03', 174, 2),
(4, 'Charles Leclerc', 'monacói', '1997-10-16', 179, 2),
(5, 'Alexander Albon', NULL, '1996-03-23', NULL, 3),
(6, 'Max Verstappen', 'holland', '1997-09-30', 180, 3),
(7, 'Daniel Ricciardo', 'ausztrál', '1989-07-01', 178, 4),
(8, 'Esteban Ocon', 'francia', '1996-09-17', 186, 4),
(9, 'Szabolcs', 'magyar', '2005-02-02', 177, 4),
(10, 'Mick Schumacher', 'német', '2001-02-07', 175, 4);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;